create table if not exists public.contacts (
    id bigint generated by default as identity primary key,
    name text not null,
    email text not null,
    message text not null,
    created_at timestamptz not null default now()
);

create table if not exists public.newsletter (
    id bigint generated by default as identity primary key,
    email text not null unique,
    created_at timestamptz not null default now()
);

create table if not exists public.visits (
    id bigint generated by default as identity primary key,
    page text,
    ip text,
    country text,
    city text,
    device text,
    browser text,
    referrer text,
    created_at timestamptz not null default now()
);

create table if not exists public.projects (
    id bigint generated by default as identity primary key,
    name text not null,
    email text not null,
    stage text,
    type text,
    details text,
    timeline text,
    budget text,
    created_at timestamptz not null default now()
);

alter table public.contacts enable row level security;
alter table public.newsletter enable row level security;
alter table public.visits enable row level security;
alter table public.projects enable row level security;
